/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : number, 'quantity' : bigint }
export interface Product {
  'name' : string,
  'unit' : string,
  'description' : string,
  'productId' : number,
  'available' : boolean,
  'imageRef' : string,
  'isInstant' : boolean,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [number, string, string, bigint, string, string, boolean],
    undefined
  >,
  'addToCart' : ActorMethod<[number, bigint], undefined>,
  'getAvailableProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[number, string, string, string], undefined>,
  'viewCart' : ActorMethod<[], Array<CartItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];