/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'productId' : IDL.Nat32,
  'available' : IDL.Bool,
  'imageRef' : IDL.Text,
  'isInstant' : IDL.Bool,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Nat32, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
  'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat32, IDL.Text, IDL.Text, IDL.Text], [], []),
  'viewCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'productId' : IDL.Nat32,
    'available' : IDL.Bool,
    'imageRef' : IDL.Text,
    'isInstant' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Nat32, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
    'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat32, IDL.Text, IDL.Text, IDL.Text], [], []),
    'viewCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };